#!/bin/bash

# Development Setup Script for InfraSafe
echo "🚀 InfraSafe Development Setup"
echo "=============================="
echo ""

echo "📋 Available Commands:"
echo ""
echo "🏗️  BUILD COMMANDS:"
echo "  npm run compile        - Compile smart contracts"
echo "  npm run build          - Build contracts + WebAuthn server"
echo "  npm run build:webauthn - Build WebAuthn server only"
echo "  npm run build:clean    - Clean and rebuild everything"
echo ""
echo "🚀 START COMMANDS:"
echo "  npm run start          - Start main InfraSafe server"
echo "  npm run start:all      - Start both servers (InfraSafe + WebAuthn)"
echo "  npm run serve          - Start InfraSafe API server only"
echo ""
echo "🔐 WEBAUTHN COMMANDS:"
echo "  npm run webauthn-server        - Start WebAuthn server (dev mode)"
echo "  npm run webauthn-server:dev    - Start WebAuthn server with nodemon"
echo "  npm run webauthn-server:start  - Start WebAuthn server (production)"
echo "  npm run webauthn-server:build  - Build WebAuthn server"
echo "  npm run webauthn-server:prod   - Start WebAuthn server (production mode)"
echo ""
echo "🧪 TESTING COMMANDS:"
echo "  npm run test           - Run smart contract tests"
echo "  npm run test:webauthn  - Run WebAuthn tests"
echo "  npm run test:all       - Run all tests"
echo "  npm run test:e2e       - Run E2E tests with Playwright"
echo ""
echo "🔧 UTILITY COMMANDS:"
echo "  npm run deploy         - Deploy contracts to localhost"
echo "  npm run deploy:testnet - Deploy contracts to testnet"
echo "  npm run node           - Start local Hardhat node"
echo "  npm run clean          - Clean build artifacts"
echo "  npm run typechain      - Generate TypeScript types"
echo ""
echo "🌐 DEVELOPMENT WORKFLOW:"
echo "  1. npm run node        (start local blockchain)"
echo "  2. npm run start:all   (start both servers)"
echo "  3. npm run test:all    (run all tests)"
echo ""
echo "📂 OUTPUTS:"
echo "  - Smart contracts: artifacts/, typechain-types/"
echo "  - WebAuthn server: dist/webauthn-server/"
echo "  - Test coverage: coverage/"
echo ""
echo "✅ Setup complete! Choose a command to get started."
